# After bootstrap terraform apply, replace <JENKINS_EC2_IP> with:
# terraform output jenkins_public_ip  (run from terraform/bootstrap/)
[jenkins]
<JENKINS_EC2_IP> ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/cloudpulse-key.pem

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
