---
- name: Add Jenkins repo
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins GPG key
  rpm_key:
    key: "{{ jenkins_gpg_key }}"

- name: Install Jenkins
  yum:
    name: "{{ jenkins_package }}"
    state: present

- name: Add jenkins user to docker group
  user:
    name: "{{ jenkins_user }}"
    groups: docker
    append: true

- name: Start and enable Jenkins
  systemd:
    name: "{{ jenkins_package }}"
    state: started
    enabled: true

- name: Create Jenkins temp directory
  file:
    path: /var/tmp/jenkins
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Configure Jenkins temp directory
  lineinfile:
    path: /usr/lib/systemd/system/jenkins.service
    regexp: '^Environment="JAVA_OPTS='
    line: 'Environment="JAVA_OPTS=-Djava.awt.headless=true -Djava.io.tmpdir=/var/tmp/jenkins"'
    backup: yes

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart Jenkins
  systemd:
    name: jenkins
    state: restarted